<script setup>
import{ref,onMounted,computed}from'vue';import{useRouter}from'vue-router';import{categories}from'../data/categories.js';import{useSeoulPlaces}from'../composables/useSeoulPlaces.js';import{useCommunityPosts}from'../composables/useCommunityPosts.js'
const router=useRouter(),features=ref([]),selected=ref(null),{places,load}=useSeoulPlaces(),{latest}=useCommunityPosts();const shown=ref(8);const project=([x,y])=>[(x-126.76)*620,(37.71-y)*760],ring=r=>r.map((p,i)=>`${i?'L':'M'}${project(p)}`).join(' ')+'Z',path=f=>(f.geometry.type==='Polygon'?f.geometry.coordinates:f.geometry.coordinates.flat(1)).map(ring).join(' '),name=f=>f?.properties?.SIG_KOR_NM;const go=d=>router.push(`/explore/${encodeURIComponent(d)}`);const count=c=>places.value.filter(p=>p.category===c).length;const visible=computed(()=>latest.value.slice(0,shown.value));
onMounted(async()=>{load();try{features.value=(await(await fetch('/data/seoul/seoul-districts.geojson')).json()).features}catch{}})
</script>
<template><div class="home"><section class="hero"><div><p class="eyebrow">공공데이터 기반 서울 지역정보 서비스</p><h1>서울을, 어디부터<br><em>둘러볼까요?</em></h1><p>서울 25개 자치구의 관광지, 문화시설, 축제와 여행 이야기를 한눈에 만나보세요.</p><a class="primary" href="#districts">지도로 시작하기 ↓</a></div><div class="hero-art"><b>SEOUL</b><span>37° 33′ N · LOCAL STORIES</span></div></section>
<section id="districts"><div class="section-head"><div><p class="eyebrow">DISTRICT EXPLORER</p><h2>궁금한 자치구를 선택해보세요</h2></div><p>지도 위 자치구를 누르면 그 지역의 장소와 이야기를 만날 수 있어요.</p></div><div class="map-wrap"><svg viewBox="0 0 410 390" aria-label="서울 자치구 지도"><path v-for="f in features" :key="name(f)" :d="path(f)" tabindex="0" :aria-label="`${name(f)} 둘러보기`" :class="{active:name(f)===name(selected)}" @mouseenter="selected=f" @focus="selected=f" @click="go(name(f))" @keydown.enter="go(name(f))" @keydown.space.prevent="go(name(f))"/></svg><aside class="district-info"><small>SELECTED DISTRICT</small><h3>{{name(selected)||'서울 25개 자치구'}}</h3><p>{{selected?'7개 카테고리의 지역 장소를 만나보세요.':'지도에서 지역을 골라보세요.'}}</p><button v-if="selected" type="button" class="primary" @click="go(name(selected))">{{name(selected)}} 둘러보기 →</button></aside></div></section>
<section><div class="section-head"><div><p class="eyebrow">EXPLORE BY CATEGORY</p><h2>취향에 맞는 서울을 골라보세요</h2></div></div><div class="category-grid"><button v-for="c in categories" :key="c.name" type="button" class="category-card" :style="{'--tone':c.tone}" @click="router.push({path:'/explore/서울전체',query:{category:c.name}})"><span>{{c.icon}}</span><small>{{count(c.name)}} PLACES</small><h3>{{c.name}}</h3><p>{{c.name}}로 만나는 새로운 서울의 표정</p><b>둘러보기 →</b></button></div></section>
<section id="community"><div class="section-head"><div><p class="eyebrow">COMMUNITY</p><h2>서울人의 최신 이야기</h2></div><p>LocalHub 이용자들이 장소에서 남긴 최신 후기를 확인해보세요.</p></div><div v-if="visible.length" class="post-grid"><article v-for="p in visible" :key="p.id" @click="router.push(`/explore/${p.district}?placeId=${p.placeId}`)"><small>{{p.category}} · {{p.district}}</small><h3>{{p.title}}</h3><p>{{p.content.slice(0,90)}}</p><span>{{p.placeName}} · 조회 {{p.views}}</span></article></div><div v-else class="empty"><b>아직 등록된 이야기가 없습니다.</b><p>서울의 장소를 둘러보고 첫 번째 후기를 남겨보세요.</p></div><button v-if="shown<latest.length" class="more" type="button" @click="shown+=8">이야기 더 보기</button></section>
<section id="about" class="data-note"><b>서울 열린데이터를 더 가깝게.</b><p>자치구 경계 GeoJSON과 브라우저 저장소를 활용한 교육용 지역정보 MVP입니다.</p></section></div></template>
